/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./app/**/*.{js,jsx}", "./components/**/*.{js,jsx}", "*.{js,jsx,mdx}", "*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Custom color palette
        pumpkin: {
          DEFAULT: "#f17105",
          100: "#301601",
          200: "#602c02",
          300: "#904203",
          400: "#c05904",
          500: "#f17105",
          600: "#fb8b2f",
          700: "#fca863",
          800: "#fdc597",
          900: "#fee2cb",
        },
        cardinal: {
          DEFAULT: "#d11149",
          100: "#2a030e",
          200: "#53071c",
          300: "#7d0a2b",
          400: "#a60d39",
          500: "#d11149",
          600: "#ee2c63",
          700: "#f2608a",
          800: "#f695b1",
          900: "#fbcad8",
        },
        selective_yellow: {
          DEFAULT: "#ffba08",
          100: "#352600",
          200: "#6a4c00",
          300: "#9f7200",
          400: "#d49800",
          500: "#ffba08",
          600: "#ffc83b",
          700: "#ffd56c",
          800: "#ffe39d",
          900: "#fff1ce",
        },
        yellow_green: {
          DEFAULT: "#b1cf5f",
          100: "#262e0e",
          200: "#4b5d1c",
          300: "#718b2a",
          400: "#97b937",
          500: "#b1cf5f",
          600: "#c0d97e",
          700: "#d0e29e",
          800: "#e0ecbf",
          900: "#eff5df",
        },
        tropical_indigo: {
          DEFAULT: "#7b89ef",
          100: "#080f40",
          200: "#101d81",
          300: "#182cc1",
          400: "#3b4fe7",
          500: "#7b89ef",
          600: "#96a0f2",
          700: "#b0b8f5",
          800: "#cad0f8",
          900: "#e5e7fc",
        },
        non_photo_blue: {
          DEFAULT: "#90e0f3",
          100: "#083946",
          200: "#10738c",
          300: "#17acd1",
          400: "#4bcbeb",
          500: "#90e0f3",
          600: "#a7e6f5",
          700: "#bdecf8",
          800: "#d3f2fa",
          900: "#e9f9fd",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
